# Generated by Django 6.1 on 2026-08-23 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('account', models.CharField(db_index=True, max_length=255)),
                ('amount', models.PositiveBigIntegerField()),
                ('purpose', models.CharField(max_length=500)),
                ('user_full_name', models.CharField(max_length=255)),
                ('return_url', models.URLField(blank=True)),
                ('callback_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plum_invoice_id', models.BigIntegerField(blank=True, null=True)),
                ('plum_unique', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('plum_valid_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('card_number', models.CharField(blank=True, max_length=32)),
                ('amount', models.PositiveBigIntegerField()),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='plum.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
